"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sample_users = exports.sample_tags = exports.sample_foods = void 0;
exports.sample_foods = [
    {
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/food-1.jpg',
        tags: ['fastfood', 'Pizza', 'Lunch'],
    },
    {
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'assets/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'assets/food-3.jpg',
        tags: ['fastfood', 'Hamburger'],
    },
    {
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'assets/food-4.jpg',
        tags: ['fastfood', 'Fry'],
    },
    {
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'assets/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-6.jpg',
        tags: ['fastfood', 'Pizza', 'Lunch'],
    },
    {
        name: 'Sushi',
        price: 15,
        cookTime: '25-35',
        favorite: true,
        origins: ['japan'],
        stars: 4.8,
        imageUrl: 'assets/food-7.jpg',
        tags: ['Sushi', 'Dinner', 'Japanese'],
    },
    {
        name: 'Pasta Carbonara',
        price: 12,
        cookTime: '20-25',
        favorite: false,
        origins: ['italy'],
        stars: 4.2,
        imageUrl: 'assets/food-8.jpg',
        tags: ['Italian', 'Dinner'],
    },
    {
        name: 'Tacos',
        price: 8,
        cookTime: '15-20',
        favorite: true,
        origins: ['mexico'],
        stars: 4.5,
        imageUrl: 'assets/food-9.jpg',
        tags: ['Mexican', 'Dinner'],
    },
    {
        name: 'Sushi Rolls',
        price: 14,
        cookTime: '30-40',
        favorite: false,
        origins: ['japan'],
        stars: 4.7,
        imageUrl: 'assets/food-10.jpg',
        tags: ['Sushi', 'Dinner', 'Japanese'],
    },
    {
        name: 'Pancakes',
        price: 6,
        cookTime: '10-15',
        favorite: true,
        origins: ['us'],
        stars: 4.0,
        imageUrl: 'assets/food-11.jpg',
        tags: ['Breakfast'],
    },
    {
        name: 'Spaghetti Bolognese',
        price: 11,
        cookTime: '25-30',
        favorite: false,
        origins: ['italy'],
        stars: 4.3,
        imageUrl: 'assets/food-12.jpg',
        tags: ['Italian', 'Dinner'],
    },
    {
        name: 'Sashimi',
        price: 18,
        cookTime: '20-25',
        favorite: true,
        origins: ['japan'],
        stars: 4.9,
        imageUrl: 'assets/food-13.jpg',
        tags: ['Sushi', 'Dinner', 'Japanese'],
    },
    {
        name: 'Burrito',
        price: 9,
        cookTime: '15-20',
        favorite: false,
        origins: ['mexico'],
        stars: 4.2,
        imageUrl: 'assets/food-14.jpg',
        tags: ['Mexican', 'Lunch'],
    },
    {
        name: 'Omelette',
        price: 7,
        cookTime: '10-15',
        favorite: true,
        origins: ['various'],
        stars: 4.1,
        imageUrl: 'assets/food-15.jpg',
        tags: ['Breakfast'],
    },
    {
        name: 'Ramen',
        price: 9,
        cookTime: '15-20',
        favorite: true,
        origins: ['japan'],
        stars: 4.6,
        imageUrl: 'assets/food-16.jpg',
        tags: ['Japanese', 'Dinner'],
    },
    {
        name: 'Cesar Salad',
        price: 8,
        cookTime: '10-15',
        favorite: false,
        origins: ['mexico', 'us'],
        stars: 3.8,
        imageUrl: 'assets/food-17.jpg',
        tags: ['Salad', 'Lunch'],
    },
    {
        name: 'Croissant',
        price: 3,
        cookTime: '10-12',
        favorite: true,
        origins: ['france'],
        stars: 4.2,
        imageUrl: 'assets/food-18.jpg',
        tags: ['French', 'Breakfast'],
    },
    {
        name: 'Tofu Stir-Fry',
        price: 10,
        cookTime: '20-25',
        favorite: false,
        origins: ['china'],
        stars: 3.9,
        imageUrl: 'assets/food-19.jpg',
        tags: ['Asian', 'Dinner'],
    },
    {
        name: 'Fajitas',
        price: 12,
        cookTime: '25-30',
        favorite: true,
        origins: ['mexico'],
        stars: 4.4,
        imageUrl: 'assets/food-20.jpg',
        tags: ['Mexican', 'Dinner'],
    },
    {
        name: 'Cheeseburger',
        price: 8,
        cookTime: '10-15',
        favorite: true,
        origins: ['us'],
        stars: 4.5,
        imageUrl: 'assets/food-21.jpg',
        tags: ['fastfood', 'Hamburger', 'Lunch'],
    },
    {
        name: 'Philly Cheesesteak',
        price: 11,
        cookTime: '15-20',
        favorite: false,
        origins: ['us'],
        stars: 4.2,
        imageUrl: 'assets/food-22.jpg',
        tags: ['fastfood', 'Dinner'],
    },
    {
        name: 'Miso Ramen',
        price: 10,
        cookTime: '20-25',
        favorite: true,
        origins: ['japan'],
        stars: 4.6,
        imageUrl: 'assets/food-23.jpg',
        tags: ['Japanese', 'Dinner', 'Soup'],
    },
    {
        name: 'Churros',
        price: 4,
        cookTime: '10-12',
        favorite: false,
        origins: ['spain'],
        stars: 3.8,
        imageUrl: 'assets/food-24.jpg',
        tags: ['Mexican'],
    },
    {
        name: 'Tuna Salad',
        price: 9,
        cookTime: '10-15',
        favorite: true,
        origins: ['various'],
        stars: 4.1,
        imageUrl: 'assets/food-25.jpg',
        tags: ['Salad', 'Lunch'],
    },
    {
        name: 'Gyoza',
        price: 7,
        cookTime: '15-20',
        favorite: false,
        origins: ['japan'],
        stars: 4.3,
        imageUrl: 'assets/food-26.jpg',
        tags: ['Japanese', 'Dinner'],
    },
    {
        name: 'Scone',
        price: 3,
        cookTime: '10-12',
        favorite: true,
        origins: ['uk'],
        stars: 3.9,
        imageUrl: 'assets/food-27.jpg',
        tags: ['Breakfast'],
    },
    {
        name: 'Veggie Wrap',
        price: 6,
        cookTime: '15-20',
        favorite: false,
        origins: ['various'],
        stars: 3.6,
        imageUrl: 'assets/food-28.jpg',
        tags: ['Lunch'],
    },
    {
        name: 'Kimchi Fried Rice',
        price: 11,
        cookTime: '20-25',
        favorite: true,
        origins: ['korea'],
        stars: 4.5,
        imageUrl: 'assets/food-29.jpg',
        tags: ['Dinner', 'Asian'],
    },
    {
        name: 'Pancetta Pasta',
        price: 12,
        cookTime: '25-30',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-30.jpg',
        tags: ['Italian', 'Dinner'],
    },
];
exports.sample_tags = [
    { name: 'All', count: 0 },
    { name: 'fastfood', count: 0 },
    { name: 'Pizza', count: 0 },
    { name: 'Lunch', count: 0 },
    { name: 'SlowFood', count: 0 },
    { name: 'Hamburger', count: 0 },
    { name: 'Fry', count: 0 },
    { name: 'Soup', count: 0 },
    { name: 'Dinner', count: 0 },
    { name: 'Italian', count: 0 },
    { name: 'Mexican', count: 0 },
    { name: 'Breakfast', count: 0 },
    { name: 'Sushi', count: 0 },
    { name: 'Japanese', count: 0 },
    { name: 'Salad', count: 0 },
    { name: 'French', count: 0 },
    { name: 'Asian', count: 0 },
];
exports.sample_users = [
    {
        name: "Liron Lin",
        email: "liron@gmail.com",
        password: "123456",
        address: "Israel",
        isAdmin: true,
    },
    {
        name: "John Doe",
        email: "john@gmail.com",
        password: "123456",
        address: "Toronto On",
        isAdmin: false,
    },
    {
        name: "Jane Doe",
        email: "Jane@gmail.com",
        password: "123456",
        address: "Shanghai",
        isAdmin: false,
    },
    {
        name: "Ola Sinilov",
        email: "ola@gmail.com",
        password: "123456",
        address: "Israel",
        isAdmin: false,
    },
];
